/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'DB_font\'">' + entity + '</span>' + html;
	}
	var icons = {
		'we_we': '&#xe60b;',
		'we_webird': '&#xe60c;',
		'we_logo': '&#xe60d;',
		'we_dashboard': '&#xe62f;',
		'we_domain': '&#xe62b;',
		'we_domainlist': '&#xe644;',
		'we_account': '&#xe640;',
		'we_sitedetails': '&#xe60e;',
		'we_admin': '&#xe63b;',
		'we_planpricing': '&#xe615;',
		'we_features': '&#xe626;',
		'we_bookmark': '&#xe633;',
		'we_mobile': '&#xe618;',
		'we_widget': '&#xe60f;',
		'we_whatnext': '&#xe611;',
		'we_newstar': '&#xe617;',
		'we_globalsetting': '&#xe61f;',
		'we_plan': '&#xe63d;',
		'we_menu': '&#xe619;',
		'we_surveybranching': '&#xe612;',
		'we_check': '&#xe632;',
		'we_attachment': '&#xe634;',
		'we_hook': '&#xe61e;',
		'we_arr_up': '&#xe635;',
		'we_arr_down': '&#xe638;',
		'we_arr_left': '&#xe637;',
		'we_arr_right': '&#xe636;',
		'we_prev': '&#xe613;',
		'we_next': '&#xe614;',
		'we_dd_left': '&#xe62e;',
		'we_dd_right': '&#xe62d;',
		'we_dd_down': '&#xe66c;',
		'we_dd_up': '&#xe600;',
		'we_cross': '&#xe630;',
		'we_notification': '&#xe616;',
		'we_allnotification': '&#xe63a;',
		'we_addnew': '&#xe63c;',
		'we_setting': '&#xe61a;',
		'we_active': '&#xe63f;',
		'we_draft': '&#xe629;',
		'we_expired': '&#xe627;',
		'we_postdated': '&#xe61b;',
		'we_inactive': '&#xe61d;',
		'we_layout': '&#xe61c;',
		'we_survey': '&#xe620;',
		'we_allsurvey': '&#xe639;',
		'we_feedback': '&#xe624;',
		'we_inbox': '&#xe621;',
		'we_stats': '&#xe622;',
		'we_f_resolved': '&#xe668;',
		'we_addfeedback': '&#xe646;',
		'we_like': '&#xe623;',
		'we_resolved': '&#xe625;',
		'we_suggestion': '&#xe628;',
		'we_question': '&#xe62a;',
		'we_problem': '&#xe62c;',
		'we_reports': '&#xe631;',
		'we_copy': '&#xe63e;',
		'we_form': '&#xe641;',
		'we_statistics': '&#xe642;',
		'we_routing': '&#xe643;',
		'we_mail': '&#xe645;',
		'we_whitelabel': '&#xe647;',
		'we_embedfeedbk': '&#xe648;',
		'we_delete': '&#xe649;',
		'we_view': '&#xe64a;',
		'we_newbig': '&#xe651;',
		'we_feedbacknew': '&#xe64b;',
		'we_clock': '&#xe64c;',
		'we_waiting': '&#xe64d;',
		'we_logout': '&#xe64e;',
		'we_targeting': '&#xe650;',
		'we_back': '&#xe652;',
		'we_front': '&#xe653;',
		'we_newview': '&#xe654;',
		'we_click': '&#xe655;',
		'we_information': '&#xe656;',
		'we_search': '&#xe657;',
		'we_revert': '&#xe658;',
		'we_edit': '&#xe659;',
		'we_save': '&#xe65a;',
		'we_clickrate': '&#xe65b;',
		'we_attempted': '&#xe65c;',
		'we_completed': '&#xe65d;',
		'we_responserate': '&#xe65e;',
		'we_globe': '&#xe660;',
		'we_displayed': '&#xe662;',
		'we_history': '&#xe661;',
		'we_configuration': '&#xe65f;',
		'we_superman': '&#xe663;',
		'we_unread': '&#xe666;',
		'we_details': '&#xe667;',
		'we_transfer': '&#xe669;',
		'we_dash': '&#xe66a;',
		'we_geo': '&#xe66b;',
		'we_download': '&#xe66d;',
		'we_upload': '&#xe66e;',
		'we_update': '&#xe66f;',
		'we_calender': '&#xe670;',
		'we_resume': '&#xe671;',
		'we_pause': '&#xe672;',
		'we_lock': '&#xe673;',
		'we_pdf': '&#xe674;',
		'we_xls': '&#xe675;',
		'we_link': '&#xe676;',
		'we_read': '&#xe677;',
		'we_newclicks': '&#xe678;',
		'we_more': '&#xe679;',
		'we_newresponses': '&#xe67a;',
		'we_cancelthin': '&#xe67b;',
		'we_minus': '&#xe67c;',
		'we_move': '&#xe67d;',
		'we_toggle': '&#xe67e;',
		'we_negative': '&#xe67f;',
		'we_positive': '&#xe680;',
		'we_neutral': '&#xe681;',
		'we_userdefined': '&#xe64f;',
		'we_custinsigts': '&#xe682;',
		'we_ecomm': '&#xe683;',
		'we_leadgen': '&#xe684;',
		'we_custaquisation': '&#xe685;',
		'we_funnel': '&#xe687;',
		'we_f_percent': '&#xe688;',
		'we_skype': '&#xe604;',
		'we_help': '&#xe605;',
		'we_goal': '&#xe603;',
		'we_Conversionlist': '&#xe609;',
		'we_goalsstats': '&#xe60a;',
		'we_skypel': '&#xe606;',
		'we_play': '&#xe602;',
		'we_wysiwyt_onvideo': '&#xe607;',
		'we_iphone': '&#xe601;',
		'we_tick': '&#xe608;',
		'we_font-02': '&#xe610;',
		'we_font-03': '&#xe664;',
		'we_font-01': '&#xe665;',
		'we_funarrow': '&#xe686;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/we_[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
